"""
Luna AI Core Prompts
Tier 1 (70% capability)
"""
from .global_system import PROMPT_NAME as GLOBAL_SYSTEM, PROMPT_INFO as GLOBAL_SYSTEM_INFO
from .instagram_expert import PROMPT_NAME as INSTAGRAM_EXPERT, PROMPT_INFO as INSTAGRAM_EXPERT_INFO
from .consultation_methodology import PROMPT_NAME as CONSULTATION_METHODOLOGY, PROMPT_INFO as CONSULTATION_METHODOLOGY_INFO

__all__ = [
    "GLOBAL_SYSTEM",
    "GLOBAL_SYSTEM_INFO",
    "INSTAGRAM_EXPERT",
    "INSTAGRAM_EXPERT_INFO",
    "CONSULTATION_METHODOLOGY",
    "CONSULTATION_METHODOLOGY_INFO",
]
