"""
Luna AI Advanced Prompts
Tier 3 (95% capability)
"""
from .audience_analysis import PROMPT_NAME as AUDIENCE_ANALYSIS, PROMPT_INFO as AUDIENCE_ANALYSIS_INFO
from .competitive_intelligence import PROMPT_NAME as COMPETITIVE_INTELLIGENCE, PROMPT_INFO as COMPETITIVE_INTELLIGENCE_INFO
from .growth_acceleration import PROMPT_NAME as GROWTH_ACCELERATION, PROMPT_INFO as GROWTH_ACCELERATION_INFO
from .realtime_research import PROMPT_NAME as REALTIME_RESEARCH, PROMPT_INFO as REALTIME_RESEARCH_INFO

__all__ = [
    "AUDIENCE_ANALYSIS",
    "AUDIENCE_ANALYSIS_INFO",
    "COMPETITIVE_INTELLIGENCE",
    "COMPETITIVE_INTELLIGENCE_INFO",
    "GROWTH_ACCELERATION",
    "GROWTH_ACCELERATION_INFO",
    "REALTIME_RESEARCH",
    "REALTIME_RESEARCH_INFO",
]
